Traceback (most recent call last):
  File "c:\Users\rafael.luna\Desktop\docs pessoais\Projects\BotBlaze\BotBlaze\Bot_completo.py", line 169, in <module>
    Bot.EsperarLance()
  File "c:\Users\rafael.luna\Desktop\docs pessoais\Projects\BotBlaze\BotBlaze\Scripts\BlazeFunctions\Bot.py", line 73, in EsperarLance
    LanceBlazeAtual = Lances.Get(1)[0]
                      ^^^^^^^^^^^^^
  File "c:\Users\rafael.luna\Desktop\docs pessoais\Projects\BotBlaze\BotBlaze\Scripts\BlazeFunctions\Lances.py", line 18, in Get
    result_json = (requests.get(blaze_api_url)).json()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
    conn.connect()
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\urllib3\connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\urllib3\connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "C:\Users\rafael.luna\AppData\Local\anaconda3\envs\BotBlaze\Lib\site-packages\urllib3\util\ssl_.py", line 444, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir, ca_cert_data)
KeyboardInterrupt
